version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 "app:create_app()"
    volumes:
      - ./project:/app
    expose:
      - 5000
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  nginx:
    build: ./nginx
    ports:
      - "80:80" # Change to "443:443" for HTTPS
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: